### PR TITLE
Add 'rebootable' tag to all nodes except 'unique'

### PR DESCRIPTION
**Pull request by dmick**
This corresponds to a change in the ceph-build-pull-requests
job to request a rebootable node

Signed-off-by: Dan Mick <dan.mick@redhat.com>

### CODE REVIEW

**Comment by dmick** [comment]
This was originally a PR against a fork in github.com/ceph/mita.  Alfredo would like to make that repo not be a fork but rather be the official repo.

Copying some of the discussion from that PR:

@alfredodeza: I might be missing a bit from the discussion yesterday, but I thought the idea of the new rebootable label was to allow the ceph-pull-requests job have a better selection of the nodes preventing a situation where a node with a matching subset of labels would be servicing the job.

However, this label is being applied to every node except for the ones with the unique label. Can you explain why this is needed on all those nodes?

I think that rather than changing all the other nodes, we should add two nodes that have and service the bootable label. For example Centos7 would be:

'centos7_huge_rebootable': {
    'script': dedent("""#!/bin/bash
    curl -u {{ prado_user | default('admin') }}:{{ prado_token }} -L "{{ prado_url }}/setup/slave/?token={{ jenkins_prado_token }}&executors=2&labels=rebootable+amd64+centos7+huge+x86_64&nodename=centos7_huge_rebootable__%s" | bash"""),
    'keyname': keyname,
    'image_name': 'Centos 7',
    'size': 'hg-30',
    'labels': ['amd64', 'x86_64', 'centos7', 'huge', 'rebootable'],
    'provider': 'openstack'
},

And we would add another one for trusty "huge". That would add two more configs and leave everything else as-is

@dmick: All the nodes marked are rebootable. It's not aimed at one particular job; it's designed to distinguish mita nodes from physical nodes. Other tags further qualify the nodes for ceph-p-r. 

@alfredodeza:  Adding rebootable to nodes to distinguish them as "mita nodes" doesn't read right, since it is leaving out nodes that are labeled as "unique". Those nodes are also mita nodes.

If nodes need to have some identifier to differentiate them from "created by mita" vs. "other nodes" on a label-basis I think we should have a label that describes just that

@dmick: No,the label describes exactly the attribute of the nodes that matters. I left out the unique nodes because unique is already muddy as a tag. 

@andrewschoen: is the main goal here to keep the arm64 nodes from being selected by ceph-pull-requests and not risk the chance of being rebooted? Perhaps just adding x86_64 to nodes on that job would solve that.

https://github.com/ceph/ceph-build/blob/master/ceph-pull-requests/config/definitions/ceph-pull-requests.yml#L6

So it would become: huge && x86_64 && (centos7 || trusty)

@dmick: No,the goal is to describe the attribute of the node that makes it different and desirable.  That's only true today for one job, but the point is to be clear and explicit. 

@alfredodeza:  I am not disagreeing in adding more labels. The more labels and the more they can describe attributes of a node the better.

We shouldn't drag the discussion around the unique label because that was a thing that we tried to implement quickly out of despair (it needs to be revisited for sure).

Because we are adding a new architecture (arm64/aarch64) then I think that it would be best to declare on other jobs, explicitly, "x86_64" or "amd64" (they are both present currently on every node).

It is reasonable for other jobs now to be burdened with having to "ask for the explicit arch it needs".

Would you mind adding those to this PR aside from the rebootable label? 

@dmick: Well, I think the jobs that require x86_64 already ask for it, but I'll review. Part of the point here is that especially if we're dedicating physical ARM hosts as slaves, there's no reason they can't run architecture-independent or distro-independent jobs too.

**Comment by dmick** [comment]
Now looking at the jobs which do or don't request x86_64

**Comment by alfredodeza** [comment]
@dmick do you want to prevent moving forward with this PR until you have looked at the other jobs that relate to `x86_64` ?

**Comment by dmick** [comment]
I think that's separable, unless I'm missing something?

**Pull request merged**
